# Generated by Django 5.0 on 2023-12-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ceratead',
            new_name='created',
        ),
    ]
