# Generated by Django 5.0 on 2023-12-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_enlace_alter_project_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='enlace',
            new_name='link',
        ),
    ]
